const dtbVideos = [
  {
    id: 1,
    userId: 8,
    cap: "The legendary place 🤯 #googleearth #googlemaps #googlemapsfun",
    music: "som original - probability",
    videoSrc: require('./Videos/googlemapfun_video1.mp4'),
    hearts: "2.2M",
    comments: "7.9M",
    shares: "1.2M",
    horizontal: true,
  },
  {
    id: 2,
    userId: 9,
    cap: "te fiti..🏞️❤️#moana #tefiti #fyp",
    music: "เสียงต้นฉบับ - 🖤ˢᴬᴰ ˢᵀᴼᴿᵞ🖤",
    videoSrc: require('./Videos/menust_video1.mp4'),
    hearts: "1.4M",
    comments: "4176",
    shares: "7606",
    horizontal: true,
  },
  {
    id: 3,
    userId: 10,
    cap: "",
    music: "nhạc nền - NGUYỄN AN 444",
    videoSrc: require('./Videos/annguyenj444_video1.mp4'),
    hearts: "423.2K",
    comments: "4627",
    shares: "28.5K",
    horizontal: false,
  },
  {
    id: 4,
    userId: 11,
    cap: "Bạn không nên chỉ có một chiếc GTR trong lòng và Mercedes-Benz AMG-GTR #amg #gtr #performance",
    music: "nhạc nền - Nhật Anh👑",
    videoSrc: require('./Videos/ndc_8888_video1.mp4'),
    hearts: "110.3K",
    comments: "470",
    shares: "35.2K",
    horizontal: true,
  },
  {
    id: 5,
    userId: 12,
    cap: "Inst: tusya_kiskis",
    music: "original sound - Daniela Estalagem",
    videoSrc: require('./Videos/_tusya_kiskis_video1.mp4'),
    hearts: "5.4M",
    comments: "48.5K",
    shares: "138.2K",
    horizontal: false,
  },
  {
    id: 6,
    userId: 1,
    cap: "Một lượng vốn đến từ các quỹ ngoại đang chờ đợi đầu tư vào các doanh nghiệp khởi nghiệp trong lĩnh vực #blockchain tại Việt Nam #vtvdigital #vtv24",
    music: "original sound - VTV24",
    videoSrc: require('./Videos/vtv24news_video1.mp4'),
    hearts: "3.4M",
    comments: "38.5K",
    shares: "158.2K",
    horizontal: false,
  },
  {
    id: 7,
    userId: 2,
    cap: "Không ngờ luôn 😳 #caocuongvu #vulaci #learnontiktok #hoccungtiktok",
    music: "nhạc nền - caocuongvu",
    videoSrc: require('./Videos/caocuongvu_video1.mp4'),
    hearts: "662.7K",
    comments: "3.5K",
    shares: "15.2K",
    horizontal: false,
  },
  {
    id: 8,
    userId: 3,
    cap: "Don’t break my 🖤 :))) vì ko dễ vỡ đou :)))))) #DBMH dc:@spacex.dancegroup",
    music: "Dont Break My Heart - Binz",
    videoSrc: require('./Videos/cciinnn_video1.mp4'),
    hearts: "66.7K",
    comments: "32.5K",
    shares: "15.4K",
    horizontal: false,
  },
  {
    id: 9,
    userId: 4,
    cap: "Thầy giáo bất lực #dotiendat",
    music: "nhạc nền - Đỗ Đạt",
    videoSrc: require('./Videos/datdo0803_video1.mp4'),
    hearts: "626.7K",
    comments: "325.5K",
    shares: "25.4K",
    horizontal: false,
  },
  {
    id: 10,
    userId: 5,
    cap: "1 mình 1 chiến hạm :))) không có ghế nhựa nên phải vác quả ghế kia",
    music: "Cool Ngầu (Short Version) - Robi & VieEnt",
    videoSrc: require('./Videos/hoaa.hanassii_video1.mp4'),
    hearts: "426.7K",
    comments: "35.5K",
    shares: "5.4K",
    horizontal: false,
  },
  {
    id: 11,
    userId: 6,
    cap: "Layer vuông 😛 #sinhanh #tocdep #tóc #xuhuong #uốntoc #nhuộmtóc #cắtlayer #hair #stylist #mullet #cattoc #dalali",
    music: "Gatal - Janna Nick",
    videoSrc: require('./Videos/sinhanh.hair_video1.mp4'),
    hearts: "4.3M",
    comments: "15.5K",
    shares: "2.4K",
    horizontal: false,
  },
  {
    id: 12,
    userId: 7,
    cap: "Thiên An hiếm hoi nhắc về Jack khi biết mình mang thai, tiết lộ hành trình một mình nuôi con #tiinnews #thienan #jack",
    music: "nhạc nền - Tiin.vn",
    videoSrc: require('./Videos/tiin.vn_video1.mp4'),
    hearts: "332.5K",
    comments: "5.5K",
    shares: "3.4K",
    horizontal: false,
  },
];

export default dtbVideos;