const dtbVideos = [
  {
    id: 1,
    userId: 8,
    cap: "The legendary place 🤯 #googleearth #googlemaps #googlemapsfun",
    music: "som original - probability",
    videoSrc: require('./Videos/googlemapfun_video1.mp4'),
    hearts: "2.2M",
    comments: "7.9M",
    shares: "1.2M",
    horizontal: true,
  },
  {
    id: 2,
    userId: 9,
    cap: "te fiti..🏞️❤️#moana #tefiti #fyp",
    music: "เสียงต้นฉบับ - 🖤ˢᴬᴰ ˢᵀᴼᴿᵞ🖤",
    videoSrc: require('./Videos/menust_video1.mp4'),
    hearts: "1.4M",
    comments: "4176",
    shares: "7606",
    horizontal: true,
  },
  {
    id: 3,
    userId: 10,
    cap: "",
    music: "nhạc nền - NGUYỄN AN 444",
    videoSrc: require('./Videos/annguyenj444_video1.mp4'),
    hearts: "423.2K",
    comments: "4627",
    shares: "28.5K",
    horizontal: false,
  },
  {
    id: 4,
    userId: 11,
    cap: "14/2 bạn muốn tôi tặng quà gì cho bạn. #Lamborghini #lamborghinisvj #14 #suhuong",
    music: "suara asli - Chitanda Eru 愛 - MUGIWARA 愛",
    videoSrc: require('./Videos/ndc_8888_video1.mp4'),
    hearts: "610.3K",
    comments: "4670",
    shares: "3543",
    horizontal: false,
  },
  {
    id: 5,
    userId: 12,
    cap: "Inst: tusya_kiskis",
    music: "original sound - Daniela Estalagem",
    videoSrc: require('./Videos/_tusya_kiskis_video1.mp4'),
    hearts: "5.4M",
    comments: "48.5K",
    shares: "138.2K",
    horizontal: false,
  },
];

export default dtbVideos;